version: '3.9'
services:
  backend:
    build:
      context: ./backend
    command: ["deno", "run", "--inspect", "--allow-all", "server.ts"]
    ports:
      - "8000:8000" # Adjust to your backend port
    volumes:
      - ./backend:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/mydatabase" # Key: Value pair

  frontend:
    build:
      context: ./frontend
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000" # Adjust to your frontend dev server port
    volumes:
      - ./frontend:/app
    working_dir: /app
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500 
      - WATCHPACK_POLLING=true

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
